### ISSUE TITLE
PATCH seems broken

### ISSUE THREAD

**Issue by michielbdejong** [pdsinterop/community-server#8]
It seems that CSS is just not executing the sparql-update instructions (but maybe there is a header missing or a syntax error in the request somewhere?).
See:
* https://github.com/michielbdejong/community-server/runs/1863474032#step:13:125
* https://github.com/michielbdejong/community-server/runs/1863474032#step:13:105

**Comment by ylebre** [comment]
A few lines before, it looks like it is failing to parse the sparql:
2021-02-09T13:48:16.104Z [SparqlUpdateBodyParser] warn: Could not translate SPARQL query to SPARQL algebra

I've checked the patches that the test suite is doing, listing them here:
```
165:
INSERT DATA { <#that> a <#fact> . }

227: (fails)
DELETE DATA { <#hello> <#linked> <#world> . }
INSERT DATA { <#that> a <#fact> . }

287:
DELETE DATA { <#something> <#completely> <#different> . }
INSERT DATA { <#that> a <#fact> . }

346: (fails)
DELETE DATA { <#hello> <#linked> <#world> . }

399:
DELETE DATA { <#something> <#completely> <#different> . }
```

If I'm reading it correctly, the sparql parser fails on the same DELETE statement both times:
DELETE DATA { <#hello> <#linked> <#world> . }

**Comment by ylebre** [comment]
After some more digging, I'm not sure that my previous idea is correct.

Running on my local install, I get an error back from the PATCH request:
UnsupportedHttpError: Cannot resolve relative IRI #hello because no base IRI was set.

**Comment by michielbdejong** [comment]
> UnsupportedHttpError: Cannot resolve relative IRI #hello because no base IRI was set.
Was that error in the test-suite or in CSS? I can't reproduce it doing curl against CSS

**Comment by michielbdejong** [comment]
Looking into `Using PATCH to remove triple (present)`; marking it as skip until we find a fix.

**Comment by michielbdejong** [comment]
Also `Update › Using PATCH to replace triple (present) › updates the resource`.

**Comment by michielbdejong** [comment]
This took me a long time to figure out: https://github.com/solid/community-server/issues/614 :)

**Comment by michielbdejong** [comment]
There's now only one PATCH test still failing, and that's the one related to https://github.com/solid/specification/issues/234
